# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Ubuntu x64

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./src/StringComparison/StringComparison.csproj
      
    - name: Build
      run: dotnet build ./src/StringComparison/StringComparison.csproj --no-restore
      
    - name: Test
      run: dotnet test ./src/StringComparison.Test/StringComparison.Test.csproj --no-build --no-restore --verbosity normal
